version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: gem install bundler:2.2.26
      - ruby/bundle-install
      - run:
          name: Run rspec tests
          command: bundle exec rake spec
workflows:
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              # https://github.com/CircleCI-Public/cimg-ruby
              # only supports the last three ruby versions
              ruby-version: ["2.5.1", "2.6.5"]
